using DataObjects.LogInOutBO;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using MTNBaseClasses.BaseClasses.MasterTerminal;
using MTNForms.Controls;
using MTNForms.FormObjects;
using MTNForms.FormObjects.General_Functions;
using MTNForms.FormObjects.Misc;
using MTNForms.FormObjects.System_Items.System_Ops;
using MTNGlobal;
using MTNGlobal.EnumsStructs;
using MTNUtilityClasses.Classes;

namespace MTNAutomationTests.TestCases.Master_Terminal.Opsview_Tests
{
    [TestClass, TestCategory(TestCategories.MTN)]
    public class TestCase50284 : MTNBase
    {

        [ClassInitialize]
        public static void ClassInitialize(TestContext testContext) => BaseClassInitialize_New(testContext);

        [TestInitialize]
        public new void TestInitialize() {}

        [TestCleanup]
        public new void TestCleanup() => base.TestCleanup();

        void MTNInitialize()
        {
            // Set userName variable (moved from ClassInitialize)
            userName = "MTN-OPS";

            // Initialize data and log in using the new pattern
            LogInto<MTNLogInOutBO>(userName);
        }

        [TestMethod]
        public void AddUpdateDeleteTrade()
        {
            MTNInitialize();
            
            // Navigate to System Admin | Terminal table
            FormObjectBase.NavigationMenuSelection(@"System Ops| System Admin");
            SystemAdminForm systemAdminForm1 = new SystemAdminForm(@"System Administration");
            //MTNControlBase.SetValue(systemAdminForm1.cmbTable, @"Trades");
            systemAdminForm1.cmbTable.SetValue(@"Trades");

            // Click New button
            //systemAdminForm1.btnNew.DoClick();
            systemAdminForm1.DoNew();

            // Enter Description - Opsview Trade
            MTNControlBase.SetValueInEditTable(systemAdminForm1.tblDetails, @"Description", @"Opsview Trade");

            // Click the Save button
            systemAdminForm1.DoSave();

            // close the form
            systemAdminForm1.CloseForm();

            // Navigate to System Admin | Terminal table
            FormObjectBase.NavigationMenuSelection(@"System Ops| System Admin", true);
            SystemAdminForm systemAdminForm = new SystemAdminForm(@"System Administration");
            //MTNControlBase.SetValue(systemAdminForm.cmbTable, @"Trades");
            systemAdminForm.cmbTable.SetValue(@"Trades");

            //MTNControlBase.FindClickRowInTable(systemAdminForm.tblAdministrationItems, @"Description^Opsview Trade", clickType: ClickType.DoubleClick, searchType: SearchType.Exact);
            systemAdminForm.TblAdministrationItemsRH16A.FindClickRow(["Description^Opsview Trade"], clickType: ClickType.DoubleClick, searchType: SearchType.Exact);

            // Click Edit button
            systemAdminForm.DoEdit();

            // Change Description 
             MTNControlBase.SetValueInEditTable(systemAdminForm.tblDetails, @"Description", @"Opsview Trade updated");

            // Click Save button
            systemAdminForm.DoSave();

            // Delete the trade
            systemAdminForm.DoDelete();

            // Open General Functions | Activity History 
            FormObjectBase.NavigationMenuSelection(@"General Functions | Activity History");

            // Click Find button on Searcher
            Activity_History_Form activityHistoryForm = new Activity_History_Form(@"Activity History MTNQ");
            //activityHistoryForm.btnFind.DoClick();
            activityHistoryForm.DoFind();

            // Click Terminal Activity button
            //activityHistoryForm.btnTerminalActivity.DoClick();
            activityHistoryForm.DoTerminalActivity();

            // Find and double Click the row to check the message generated by opsview BGP
            //activityHistoryForm.GetInformationTable();
             /*MTNControlBase.FindClickRowInTable(activityHistoryForm.tblInformation,
                 @"Terminal^System~Type^External Interface~Status^Sent - Timed Out~User^ADMIN~Interface Name^opsview",
                 ClickType.DoubleClick, SearchType.Exact, 1, 18, 3);*/
            activityHistoryForm.TblInformation.FindClickRow(
                ["Terminal^System~Type^External Interface~Status^Sent - Timed Out~User^ADMIN~Interface Name^opsview"],
                ClickType.DoubleClick, SearchType.Exact,  rowInstance: 3);
                        
            // Check the message is created as expected for Trade Create
            string[] stringsToFind1 =
            {
                   @"tableName: ref_carrier_service",
                   @"carrier_mode: VESSEL",
                   @"life_cycle_state: ACT",
                   @"name: Opsview Trade",
                   @"updateAction: C",
                   @"updateType: TRADE"
              };
            Activity_History_Extra_Detail_Form extraDetailsFormCreate = new Activity_History_Extra_Detail_Form(@"opsview POST testurl.org was sent");
            extraDetailsFormCreate.CreateFilesToCheckDetails(@"50284_File1", @"50284_File2", stringsToFind1);

            // Check the message is created as expected for Trade Update
            activityHistoryForm.SetFocusToForm();
            // MTNControlBase.FindClickRowInTable(activityHistoryForm.tblInformation, @"Terminal^System~Type^External Interface~Status^Sent - Timed Out~User^ADMIN~Interface Name^opsview", ClickType.DoubleClick, SearchType.Exact, 1, 18, 2);
            activityHistoryForm.TblInformation.FindClickRow(
                ["Terminal^System~Type^External Interface~Status^Sent - Timed Out~User^ADMIN~Interface Name^opsview"],
                ClickType.DoubleClick, SearchType.Exact, rowInstance: 2);
            string[] stringsToFind2 =
            {
                   @"tableName: ref_carrier_service",
                   @"carrier_mode: VESSEL",
                   @"life_cycle_state: ACT",
                   @"name: Opsview Trade updated",
                   @"updateAction: U",
                   @"updateType: TRADE"
              };
            Activity_History_Extra_Detail_Form extraDetailsFormUpdate = new Activity_History_Extra_Detail_Form(@"opsview POST testurl.org was sent");
            extraDetailsFormUpdate.CreateFilesToCheckDetails(@"50284_File1", @"50284_File2", stringsToFind2);

            // Check the message is created as expected for Trade Update
            activityHistoryForm.SetFocusToForm();
            // MTNControlBase.FindClickRowInTable(activityHistoryForm.tblInformation, @"Terminal^System~Type^External Interface~Status^Sent - Timed Out~User^ADMIN~Interface Name^opsview", ClickType.DoubleClick, SearchType.Exact, 1, 18, 1);
            activityHistoryForm.TblInformation.FindClickRow(
                ["Terminal^System~Type^External Interface~Status^Sent - Timed Out~User^ADMIN~Interface Name^opsview"],
                ClickType.DoubleClick, SearchType.Exact, rowInstance: 1);
            string[] stringsToFind3 =
            {
                   @"tableName: ref_carrier_service",
                   @"updateAction: D",
                   @"updateType: TRADE"
              };
            Activity_History_Extra_Detail_Form extraDetailsFormDelete = new Activity_History_Extra_Detail_Form(@"opsview POST testurl.org was sent");
            extraDetailsFormDelete.CreateFilesToCheckDetails(@"50284_File1", @"50284_File2", stringsToFind3);


        }
    }
}
